name: Build Kiwi Mod APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y wget unzip zipalign apksigner openjdk-11-jdk curl jq

    - name: Download latest Kiwi APK
      run: |
        mkdir -p build
        URL=$(curl -s https://api.github.com/repos/kiwibrowser/src.next/releases/latest \
        | jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url' | head -n 1)
        echo "Downloading: $URL"
        wget -O build/kiwi.apk "$URL"

    - name: Generate keystore
      run: |
        keytool -genkey -v \
        -keystore build/key.jks \
        -alias kiwi \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass password \
        -keypass password \
        -dname "CN=Kiwi,O=Android,C=US"

    - name: Align APK
      run: |
        zipalign -f 4 build/kiwi.apk build/kiwi-aligned.apk

    - name: Sign APK
      run: |
        apksigner sign \
        --ks build/key.jks \
        --ks-pass pass:password \
        --key-pass pass:password \
        build/kiwi-aligned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kiwi-mod-apk
        path: build/kiwi-aligned.apk
